Add GeoIP and GeoSite support for expr
apernet/OpenGFW pull request #38
Opened 2024-01-28 14:42 UTC by KujouRinka

I add geoip and geosite support:

```yaml
- name: geosite block bilibili
  action: block
  expr: geosite(string(tls?.req?.sni), "bilibili")

- name: geoip block some ip
  action: block
  expr: geoip(string(ip.dst), "cn")
```

But I think it's better to make this as a draft, for more things that might have further discussion:
- Most of files are directly copied from `github.com/apernet/hysteria/extras/acl`, I think only part of them are used so I decide to remove code that don't be used;
- I have no idea about could I organize file like this and file naming convention;
- More geo-like function could be added, such as CIDR support.

2024-01-28 22:56 UTC, tobyxdd reviewed
Much thanks for the PR, but I think there are a few issues:

- It seems like the entire ACL system from Hysteria is ported here? I'm not sure if we need all this except `matchers_v2geo.go` (and the `v2geo` package for parsing the data format). I think `geo_matcher.go` should contain the logic for creating and managing geoip/geosite matchers directly, instead of relying on `compileHostMatcher`, so we can remove the whole ACL compilation system, which contains a lot of code we don't need.
- Maybe we should put geoip/geosite & all future built-in functions into a subpackage of `ruleset`
- Need a way to expose config options for users to specify local geoip/geosite db files, similar to Hysteria.
- Correct me if I'm wrong but I think `GeoMatcher` has to be thread-safe? The ruleset can be called by multiple workers processing multiple streams at the same time.

2024-01-29 02:45 UTC, KujouRinka commented
Here's what I do:
- Remove most of files but keep `v2geo` and `matchers_v2geo.go`;
- Rename `matcher.go` to `host_matchers.go` for I think this is helpful;
- I only keep `compileHostMatcher` function from `compile.go` and move it to `geo_matcher.go`;
- Add `Mutex` to protect field in `GeoMatcher`, but I think it may be better to use `RwLock` instead.

So it looks like:
```
ruleset
    ├── buildins
    │   └── geo
    │       ├── geo_loader.go
    │       ├── geo_matcher.go
    │       ├── host_matchers.go
    │       ├── interface.go
    │       ├── matchers_v2geo.go
    │       └── v2geo/
    ├── expr.go
    └── interface.go
```

If no further problem, I will continue working on this:
> Need a way to expose config options for users to specify local geoip/geosite db files, similar to Hysteria.

But may I ask that it's better to put this option to `config.yaml` in `rules.yaml`?

Thanks for your reading.

2024-01-29 03:00 UTC, tobyxdd commented
👍 The changes look good but maybe remove `compileHostMatcher` entirely (extract the code that handles geoip/geosite into separate methods in `GeoMatcher`). btw "buildins" should be "builtins".

> But may I ask that it's better to put this option to config.yaml in rules.yaml?

In `config.yaml`, perhaps create a new section for ruleset settings as we may have more in the future

2024-01-29 03:03 UTC, tobyxdd commented
```go
func NewGeoLoader() (*GeoMatcher, error) {
```

Is this a typo? It should be `NewGeoMatcher`

2024-01-29 03:05 UTC, tobyxdd requested changes

2024-01-29 03:05 UTC, tobyxdd commented on ruleset/buildins/geo/geo_matcher.go
> +func NewGeoLoader() (*GeoMatcher, error) {
Is this a typo? I assume it should be `NewGeoMatcher`

2024-01-29 03:05 UTC, tobyxdd commented on ruleset/buildins/geo/host_matchers.go
Do we need this file? I don't think we use any matchers from here

2024-01-29 03:26 UTC, KujouRinka commented on ruleset/buildins/geo/geo_matcher.go
> +func NewGeoLoader() (*GeoMatcher, error) {
You are right.

2024-01-29 03:29 UTC, KujouRinka commented on ruleset/buildins/geo/host_matchers.go
After removing some unnecessary code from `compileHostMatcher`, this file can be totally removed. I will rewrite and commit it later.

2024-01-29 07:52 UTC, KujouRinka commented
To specify local geoip/geosite db files:

```yaml
# config.yaml

# other field ....

geo:
  geoip: geoip.dat
  geosite: geosite.dat
```

2024-01-29 20:18 UTC, tobyxdd requested changes

2024-01-30 02:30 UTC, tobyxdd commented on cmd/root.go
> +	Geo     cliConfigRuleset `mapstructure:"ruleset"`
Still named `Geo`

2024-01-30 03:45 UTC, KujouRinka commented
I didn't find way to lazily build geosite and geoip by only calling `expr.Compile()` so I use `parser.Parse()` and `ast.Walk` to walk on AST before compile. I also move original `expr.Compile()` 's argument to `depVisitor` but I am not sure is this right.

https://github.com/KujouRinka/OpenGFW/blob/c26e04b5a6aa5ee7f4b9405702b873a0c4b4accd/ruleset/expr.go#L104-L123

I think geosite and geoip should differ from Analyzer so I add a function `func isBuiltInFunction(name string) bool`. If I am wrong please corrent me.

2024-01-30 03:58 UTC, tobyxdd commented
Is it possible to always provide these functions when calling Compile, but only actually load the geo files when the identifier is seen by the visitor during compilation? I think this works the same, but can keep the code the way it was before

2024-01-30 04:00 UTC, tobyxdd commented on cmd/root.go
> +	Geo     cliConfigGeo     `mapstructure:"ruleset"`
Why did you rename it back... my previous comment was saying that you forgot to rename this variable to Ruleset, not asking you to change everything back to Geo 🤔

2024-01-30 04:35 UTC, KujouRinka commented on cmd/root.go
> +	Geo     cliConfigGeo     `mapstructure:"ruleset"`
Sorry for I misunderstood that.

2024-01-30 05:00 UTC, KujouRinka commented
I agree with you, but I have a more question that loading geo files may counter with internet error, while `ast.Visitor` interface doesn't provide us how to return this. I think we should introduce a field in `depVisitor` for recording.

2024-01-30 05:09 UTC, tobyxdd commented
Yes, feel free to modify depVisitor as you need.

2024-01-30 05:15 UTC, tobyxdd commented
Or maybe just keep depVisitor a visitor (only record identifiers) and do the loading in the outer compile function?

2024-01-30 05:21 UTC, KujouRinka commented
I rebase it from [1eb52f7](https://github.com/apernet/OpenGFW/pull/38/commits/1eb52f71af446376a09eab74152b4711341a3810) for making change clear.

2024-01-30 05:34 UTC, KujouRinka commented
> Or maybe just keep depVisitor a visitor (only record identifiers) and do the loading in the outer compile function?

You mean mark whether geosite and geosite is needed in `depVisitor`, then after compile function to decide whether to load?

2024-01-30 05:50 UTC, KujouRinka commented
I introduce `UseGeoSite` and `UseGeoIp` in `depVisitor` to mark this.

2024-01-30 11:10 UTC, KujouRinka commented
I think I should rebase these commits from first commit of this PR right?

2024-01-30 17:58 UTC, tobyxdd commented
> I think I should rebase these commits from first commit of this PR right?

What do you mean

2024-01-30 23:56 UTC, KujouRinka commented
I think these commits are a bit messy, so before merging, maybe I need to use "git rebase" to merge all commits into one.

2024-01-31 00:05 UTC, tobyxdd commented
That's fine, we can use squash merge.

2024-01-31 00:30 UTC, KujouRinka commented
I think this draft is about to be completed so I convert it to a PR. If have any problem, please feel free to call me. ❤️

2024-01-31 01:30 UTC, tobyxdd approved these changes

2024-01-31 01:30 UTC, merged

2024-01-31 01:31 UTC, tobyxdd commented
Thanks again for the effort. I plan to release v0.0.5 with this & WireGuard analyzer